global_parameter_server:
  ros__parameters:
    world_file: empty
    vehicle_model: iris
    num_vehicles: 2
    # Spawn locations are in ENU coordinate frame
    spawn_x:
      - 0.0
      - 0.0
    spawn_y:
      - 0.0
      - 0.3