global_parameter_server:
  ros__parameters:
    world_file: static_forest
    vehicle_model: iris
    num_vehicles: 2
    # Spawn and goal locations are in ENU coordinate frame
    spawn_x: 
      - 3.0
      - 5.0
    spawn_y:
      - 3.0
      - 5.0
    # High-level goal locations (used by the high-level planner)
    goal_x:
      - 0.0
      - 5.0
    goal_y:
      - 0.0 
      - 3.0
    goal_z:
      - 2.0 
      - 2.0
