global_parameter_server:
  ros__parameters:
    world_file: empty
    vehicle_model: iris
    num_vehicles: 4
    # Spawn and goal locations are in ENU coordinate frame
    spawn_x: 
      - 0.0
      - 0.0
      - 10.0
      - 10.0
    spawn_y:
      - 0.0
      - 10.0
      - 0.0
      - 10.0
    # High-level goal locations (used by the high-level planner)
    goal_x:
      - 10.0
      - 10.0
      - 0.0
      - 0.0
    goal_y:
      - 10.0 
      - 0.0
      - 10.0
      - 0.0
    goal_z:
      - 2.0 
      - 2.0
      - 2.0
      - 2.0

